language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode

# whitelist
branches:
  only:
    - master

before_script:
  - mysql -e 'create database myapp_test;'

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec

