require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SharingsController do

  # This should return the minimal set of attributes required to create a valid
  # Sharing. As you add validations to Sharing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SharingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sharings as @sharings" do
      sharing = Sharing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sharings).should eq([sharing])
    end
  end

  describe "GET show" do
    it "assigns the requested sharing as @sharing" do
      sharing = Sharing.create! valid_attributes
      get :show, {:id => sharing.to_param}, valid_session
      assigns(:sharing).should eq(sharing)
    end
  end

  describe "GET new" do
    it "assigns a new sharing as @sharing" do
      get :new, {}, valid_session
      assigns(:sharing).should be_a_new(Sharing)
    end
  end

  describe "GET edit" do
    it "assigns the requested sharing as @sharing" do
      sharing = Sharing.create! valid_attributes
      get :edit, {:id => sharing.to_param}, valid_session
      assigns(:sharing).should eq(sharing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sharing" do
        expect {
          post :create, {:sharing => valid_attributes}, valid_session
        }.to change(Sharing, :count).by(1)
      end

      it "assigns a newly created sharing as @sharing" do
        post :create, {:sharing => valid_attributes}, valid_session
        assigns(:sharing).should be_a(Sharing)
        assigns(:sharing).should be_persisted
      end

      it "redirects to the created sharing" do
        post :create, {:sharing => valid_attributes}, valid_session
        response.should redirect_to(Sharing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sharing as @sharing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sharing.any_instance.stub(:save).and_return(false)
        post :create, {:sharing => { "user_id" => "invalid value" }}, valid_session
        assigns(:sharing).should be_a_new(Sharing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sharing.any_instance.stub(:save).and_return(false)
        post :create, {:sharing => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sharing" do
        sharing = Sharing.create! valid_attributes
        # Assuming there are no other sharings in the database, this
        # specifies that the Sharing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sharing.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => sharing.to_param, :sharing => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested sharing as @sharing" do
        sharing = Sharing.create! valid_attributes
        put :update, {:id => sharing.to_param, :sharing => valid_attributes}, valid_session
        assigns(:sharing).should eq(sharing)
      end

      it "redirects to the sharing" do
        sharing = Sharing.create! valid_attributes
        put :update, {:id => sharing.to_param, :sharing => valid_attributes}, valid_session
        response.should redirect_to(sharing)
      end
    end

    describe "with invalid params" do
      it "assigns the sharing as @sharing" do
        sharing = Sharing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sharing.any_instance.stub(:save).and_return(false)
        put :update, {:id => sharing.to_param, :sharing => { "user_id" => "invalid value" }}, valid_session
        assigns(:sharing).should eq(sharing)
      end

      it "re-renders the 'edit' template" do
        sharing = Sharing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sharing.any_instance.stub(:save).and_return(false)
        put :update, {:id => sharing.to_param, :sharing => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sharing" do
      sharing = Sharing.create! valid_attributes
      expect {
        delete :destroy, {:id => sharing.to_param}, valid_session
      }.to change(Sharing, :count).by(-1)
    end

    it "redirects to the sharings list" do
      sharing = Sharing.create! valid_attributes
      delete :destroy, {:id => sharing.to_param}, valid_session
      response.should redirect_to(sharings_url)
    end
  end

end
